### PR TITLE
Remove amphp/file and amphp/uri dependencies

### LINKED ISSUE #78: Remove amphp/file dependency
I'm only using amphp/socket and there is following dependency tree that is useless to me:
amphp/socker -> amphp/file -> amphp/sync, amphp/parallel

So after removing this dependency, my consumers will have to install 3 packages less. 

Additionally, **replacing it with bytestream  increases performance almost 10x!**

```diff
Index: bench/HostLoaderBench.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- bench/HostLoaderBench.php	(date 1545833204000)
+++ bench/HostLoaderBench.php	(date 1545833204000)
@@ -0,0 +1,17 @@
+<?php
+
+namespace Amp\Dns\Bench;
+
+use Amp\Dns\HostLoader;
+use Amp\Loop;
+
+class HostLoaderBench
+{
+    public function benchHostLoader()
+    {
+        Loop::run(function () {
+            $loader = new HostLoader(__DIR__ . "/../test/data/hosts");
+            yield $loader->loadHosts();
+        });
+    }
+}
Index: lib/HostLoader.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/HostLoader.php	(revision 836b0896b0105298373669754ece8ad8577c0854)
+++ lib/HostLoader.php	(date 1545834232000)
@@ -2,6 +2,7 @@
 
 namespace Amp\Dns;
 
+use Amp\ByteStream\ResourceInputStream;
 use Amp\File;
 use Amp\Promise;
 use Amp\Uri\InvalidDnsNameException;
@@ -26,7 +27,8 @@
             $data = [];
 
             try {
-                $contents = yield File\get($this->path);
+                $resource = new ResourceInputStream(fopen($this->path, 'r'), filesize($this->path));
+                $contents = yield $resource->read();
             } catch (File\FilesystemException $e) {
                 return [];
             }
```

Without this change:

```
benchHostLoader               I99 P0 	[μ Mo]/r: 404.861 400.640 (μs) 	[μSD μRSD]/r: 16.964μs 4.19%

1 subjects, 100 iterations, 100 revs, 0 rejects, 0 failures, 0 warnings
(best [mean mode] worst) = 376.960 [404.861 400.640] 490.050 (μs)
⅀T: 40,486.090μs μSD/r 16.964μs μRSD/r: 4.190%
```

With this change:

```
benchHostLoader               I99 P0 	[μ Mo]/r: 46.553 44.866 (μs) 	[μSD μRSD]/r: 2.447μs 5.26%

1 subjects, 100 iterations, 100 revs, 0 rejects, 0 failures, 0 warnings
(best [mean mode] worst) = 43.520 [46.553 44.866] 54.270 (μs)
⅀T: 4,655.250μs μSD/r 2.447μs μRSD/r: 5.257%
```

### PR DESCRIPTION
**Pull request by trowski**
Replaces async loading of hosts and resolver files with blocking reads by default. An async file loader is also provided.

`HostLoader` is now an interface, therefore is a BC break, though likely would not affect most users.

The third commit uses the async loader by default if `amphp/file` is installed. Thoughts?

Closes #78.

### CODE REVIEW

**Comment by trowski** [comment]
Forgot about also removing `amphp/uri` by dropping the two functions used into this library. By including these functions in this library, we can use them in `amphp/socket` and deprecate `amphp/uri`.

**Comment by PeeHaa** [comment]
I will need to test these, but I have a feeling this is going to make it much more stable \o/

I am not entirely sure yet about the name here though. Maybe `BlockingHostLoader` to make it clear from the outside what it is / does? I will play with it a bit and see if it's more stable (at least on windows).

**Comment by trowski** [comment]
@PeeHaa I think you're right that 'blocking' is more clear, so I renamed `SyncConfigFileReader` to `BlockingConfigFileReader`. `DefaultHostLoader` is dependent on the `ConfigFileReader` instance passed, so it's not necessarily blocking.

File: lib/InvalidNameException.php [hunk 1]
```diff
@@ -0,0 +1,6 @@
+<?php
+
+namespace Amp\Dns;
+
+class InvalidNameException extends \Exception {
```
Comment (kelunik) [inline lib/InvalidNameException.php]: I think it should extend `ResolutionException`, even if `ResolutionException` is badly named, because it should be `DnsException`.

File: lib/UnixConfigLoader.php [hunk 2]
```diff
@@ -16,60 +16,73 @@ public function __construct(string $path = "/etc/resolv.conf", HostLoader $hostL
...
+        } catch (ConfigException $exception) {
+            return new Failure($exception);
+        } finally {
+            \restore_error_handler();
+        }
+
+        return new Success($fileContent);
+    }
+
     public function loadConfig(): Promise {
```
Comment (kelunik) [inline lib/UnixConfigLoader.php]: Should we make `loadConfig` final then?

Comment (trowski) [reply lib/UnixConfigLoader.php]: Done.

File: lib/Internal/Socket.php [hunk 3]
```diff
@@ -194,9 +194,9 @@ private function error(\Throwable $exception) {
             return;
         }
 
-        if (!$exception instanceof ResolutionException) {
+        if (!$exception instanceof DnsException) {
```
Comment (kelunik) [inline lib/Internal/Socket.php]: This should be `ResolutionException`.

Comment (trowski) [reply lib/Internal/Socket.php]: I blame PhpStorm. :smile: Fixed.
