### PR TITLE
Fix #120: Incorrect error message on missing domain

### LINKED ISSUE #120: Giving up resolution of 'SMTH', too many redirects
```php
<?php

use Amp\Dns\DnsConfig;
use Amp\Dns\DnsConfigLoader;
use Amp\Dns\DnsRecord;
use Amp\Dns\HostLoader;
use Amp\Dns\Rfc1035StubDnsResolver;
use function Amp\Dns\dnsResolver as dnsResolverFactory;

require_once __DIR__ . '/vendor/autoload.php';

$dnsServers = ['1.1.1.1:53'];
$dnsResolver = dnsResolverFactory(
    new Rfc1035StubDnsResolver(
        null,
        new class ($dnsServers) implements DnsConfigLoader {
            public function __construct(private readonly array $dnsServers = []) {
            }

            public function loadConfig(): DnsConfig {
                return new DnsConfig($this->dnsServers, (new HostLoader())->loadHosts());
            }
        }
    )
);

$domain = 'not.existing.domain.com';
try {
    $dnsResolver->resolve($domain, DnsRecord::A);
} catch (Throwable $e) {
    echo $e->getMessage() . PHP_EOL;
}

$domain = 'discord.com';
try {
    $dnsResolver->resolve($domain, DnsRecord::AAAA);
} catch (Throwable $e) {
    echo $e->getMessage() . PHP_EOL;
}
```

```
$ php test.php 
Giving up resolution of 'not.existing.domain.com', too many redirects
Giving up resolution of 'discord.com', too many redirects
```

When no records are retrieved from DNS, the redirect mechanism throws an DnsException.
https://github.com/amphp/dns/blob/b7515c1c41e12cbd09b1ab76872bf0b04e949142/src/Rfc1035StubDnsResolver.php#L209

### PR DESCRIPTION
**Pull request by trowski**
I expected queries for missing domains to return a response with error code NXDomain, but it seems that is not the case for some DNS servers. Rather a response containing no records is returned.

### CODE REVIEW

File: src/Rfc1035StubDnsResolver.php [hunk 1]
```diff
@@ -190,13 +190,15 @@ public function resolve(string $name, ?int $typeRestriction = null, ?Cancellatio
...
 
                     return \array_merge(...$records);
-                } catch (MissingDnsRecordException) {
-                    $alias = $this->searchForAliasRecord($searchName, $cancellation);
-                    if ($alias !== null) {
-                        $name = $alias;
-                    }
-                    continue;
                 } catch (DnsException $e) {
+                    if ($e instanceof MissingDnsRecordException) {
```
Comment (kelunik) [inline src/Rfc1035StubDnsResolver.php:194]: Why instanceof instead of a separate catch block?

Comment (trowski) [reply src/Rfc1035StubDnsResolver.php:194]: If no alias record is found, the code falls-through to the check on search index. A separate block would have to repeat that code.
